### PR TITLE
KREST-8639 Only call get on topic manager provider once

### PR DESCRIPTION
**Pull request by ehumber**
Calling get on a topic manager twice, when running in Confluent cloud, results in a Out Of Scope Exception

I'm not sure why this is - I wonder if it runs slower in this environment and as the call is async, the scope has been lost by the time the first async call to update the partition count returns, ready for us to get the topic information in the response.

### CODE REVIEW

**Review by trnguyencflt — APPROVED** [review]
LGTM

**Comment by dimitarndimitrov** [comment]
@ehumber My guess is that this would happen not just for Confluent Cloud with the thread calling the second `get()` being the one handling the result of the Admin Client call which by then is not one of our Jetty/Jersey request handling threads that contain the original request scope.

**Comment by ehumber** [comment]
> @ehumber My guess is that this would happen not just for Confluent Cloud with the thread calling the second `get()` being the one handling the result of the Admin Client call which by then is not one of our Jetty/Jersey request handling threads that contain the original request scope.

I ran embedded ce-kafka-rest locally, both as a non-docker jvm and using the docker-compose, neither saw it.

I do wonder if standalone docker-compose ce-kafka-rest pointing at a cloud backend might do.

Anyway, this fixed it in cloud, and matches the pattern of a single get call we do everywhere else.

**Comment by msn-tldr** [comment]
LGTM.

**Pull request merged**
