### PR TITLE
fix the implementation of topicExists

### PR DESCRIPTION
**Pull request by sven0726**

### CODE REVIEW

**Comment by CrazyJvm** [comment]
@sven0726 plz comment a little bit

**Comment by sven0726** [comment]
@CrazyJvm   
In our project there is a low frequency to access the partitions Kafka information, the rest api is 
GET /topics/(string: topic_name)/partitions
When there are more and more Kafka topics, about 100+, the api response time is about 10 minutes.

I found the problem is calling this function(topicExists).

**Comment by ewencp** [comment]
ok to test

**Comment by sven0726** [comment]
@ConfluentCLABot    [clabot:check]

**Comment by ewencp** [comment]
LGTM, thanks!

**Pull request merged**
