### PR TITLE
CLIENTS-281: Fix KafkaConsumerReadTask's locking, handling of multiple polls, invalid handling of old ConsumerTimeout exceptions, and incorrect generic type parameters.

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
test this please

**Comment by ewencp** [comment]
Failure is a known transient issue, retest this please

**Comment by ewencp** [comment]
Successful system test run: https://jenkins.confluent.io/job/system-test-confluent-platform-branch-builder/210/console This is against 3.2.x which we actually haven't seen this failure against, but the same issues exist in that branch since master and 3.2.x are nearly identical. I've also run this locally against master instead and did not see the hang anymore.

**Comment by mhowlett** [comment]
soft LGTM (it gets pretty complex in there)

**Pull request merged**
