### PR TITLE
Update GC settings to match Kafka, use G1

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by ijuma** [comment]
`./bin/kafka-rest-start config/kafka-rest.properties` works as expected. The Jenkins failure is unrelated as I haven't changed any code.

**Comment by ewencp** [comment]
retest this please

**Comment by ewencp** [comment]
@ijuma Same here - got lost in the shuffle, but as long as options still look up to date, LGTM.

**Comment by ijuma** [comment]
Thanks, merged.

**Pull request merged**
