### PR TITLE
Use Kafka compiled with Scala 2.11

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by ijuma** [comment]
This passed locally, not sure why it fails in Jenkins.

**Comment by ijuma** [comment]
retest this please

**Comment by ijuma** [comment]
@ewencp OK, this one is passing in Jenkins too. Is it OK to merge this and the schema-registry branch or do we need to coordinate it with other changes? Thanks.

**Comment by ewencp** [comment]
@ijuma Should be fine to just merge them all once you've got them passing tests locally.

**Pull request merged**
