### PR TITLE
Remove kafka-rest-console-scripts.

### PR DESCRIPTION
**Pull request by rigelbm**
Reason: We don't need a separate target for scripts, specially because the only scripts we have are to start and stop the server, which are useless without the rest of the server's artefacts.

Real reason: I have no idea what this is needed for, and I mostly want to see what breaks (if anything) if I delete it.

### CODE REVIEW

**Comment by rnpridgeon** [comment]
Did you verify the confluent docker images don't rely on this as the comment in this module's pom implies?

**Comment by rigelbm** [comment]
> Did you verify the confluent docker images don't rely on this as the comment in this module's pom implies?

I did check `kafka-rest-images` (not thoroughly I must say), but could not find anything. I will checkout the repo and the parent docker repo to grep (thanks Github for the very suboptimal UI).

**Review by rnpridgeon — APPROVED** [review]
LGTM pending docker verification

**Comment by rigelbm** [comment]
> LGTM pending docker verification

grepped "console-scripts" in `common-docker`, `confluent-docker-utils`, `cp-docker-images`, `docker-images`, `kafka-images`, `kafka-rest-images` and `packaging`. Not hits.

**Pull request merged**
