### PR TITLE
Error response improvements

### PR DESCRIPTION
**Pull request by AndrewJSchofield**

### CODE REVIEW

**Comment by jonchiu** [comment]
Thanks @AndrewJSchofield -- how does the linter output look like with these changes?

**Comment by AndrewJSchofield** [comment]
I'll put it through the linter today.

**Comment by AndrewJSchofield** [comment]
Successful build apart from a downstream failure unrelated to this PR.

```[ERROR] Failed to execute goal on project confluent-cloud-ksql-security: Could not resolve dependencies for project io.confluent:confluent-cloud-ksql-security:jar:7.5.0-99999: Could not find artifact io.confluent.cloud:events-schema:jar:1.155.0 in confluent-codeartifact-central (https://confluent-519856050701.dp.confluent.io/maven/maven-public/) -> [Help 1]```

**Comment by msn-tldr** [comment]
@jonchiu which linter is this? If linter is doing an OK job, we should to automate it(perhaps make it part of the build/PR process)

**Review by msn-tldr — APPROVED** [review]
+1 LGTM, since @AndrewJSchofield confirmed its a downstream build issue, unrelated to the openspec changes.

**Pull request merged**
