### PR TITLE
fix typo command line options `-help` check

### PR DESCRIPTION
**Pull request by sharego**
two $$

### CODE REVIEW

**Comment by ewencp** [comment]
ok to test

**Comment by ewencp** [comment]
Hey @sharego, this LGTM -- the failures are unrelated and seem to be due to a timing issue with the schema registry. Can you sign the [CLA](http://clabot.confluent.io/cla) and then we can merge?

**Comment by sharego** [comment]
[clabot:check]

**Comment by sharego** [comment]
[clabot:check]

**Comment by ewencp** [comment]
Thanks for the patch, @sharego!

**Pull request merged**
