### PR TITLE
fixing issue #91

### PR DESCRIPTION
**Pull request by jdehrlich**
Added a map in the avrorestproducer that will cache schemas and return the id if there is one for that schema rather than reregistering.

### CODE REVIEW

**Comment by criccomini** [comment]
Can someone look at this? We're running it in prod already.

**Comment by criccomini** [comment]
Ping

**Comment by criccomini** [comment]
@ewencp @gwenshap could someone please have a look? We've been running this patch in prod for over a month now.

**Comment by ewencp** [comment]
@criccomini @jdehrlich Sorry for the slow review. LGTM. We probably should get a real cache in there rather than a collection that can continue to grow, but schemas, of all things, shouldn't really cause any problems.

Thanks for the contribution!

**Comment by criccomini** [comment]
@ewencp assuming this will miss 3.0.1?

**Comment by ewencp** [comment]
@criccomini Unfortunately yes, and I apologize, that's my bad for not getting to the review earlier.

**Comment by ewencp** [comment]
Btw, we can cherry-pick if you want, not sure what the likelihood of a 3.0.2 is though.

**Comment by blbradley** [comment]
I made a Docker image with this patch applied. You can find it on [Docker Hub](https://hub.docker.com/r/coinsmith/cp-kafka-rest) as an automated build.

**Comment by blbradley** [comment]
For those that need this before the next release

**Pull request merged**
