### PR TITLE
KREST-2408: Try longer consumer poll in getConsumerLag integration test

### PR DESCRIPTION
**Pull request by ahuang98**
Build and tests on 7.0.x [commit](https://github.com/confluentinc/kafka-rest/commit/74f10d70138777583f4d6f6df82c557558681c04) have passed

Increasing consumer poll time to address `Consumer group offsets could not be found` failure in `getConsumerLag_returnsConsumerLag`.

https://jenkins.confluent.io/job/confluentinc/job/kafka-rest/job/master/5718/testReport/io.confluent.kafkarest.integration.v3/ConsumerLagsResourceIntegrationTest/getConsumerLag_returnsConsumerLag/
```
[2021-09-13 12:18:29,812] INFO 127.0.0.1 - - [13/Sep/2021:12:18:29 +0000] "GET /v3/clusters/lz7kmpQcRlmmyZFgDkR4JA/consumer-groups/consumer-group-1/lags/topic-1/partitions/0 HTTP/1.1" 404 73 "-" "Jersey/2.34 (HttpUrlConnection 1.8.0_292)" 94 (io.confluent.rest-utils.requests:62)
[2021-09-13 12:18:36,418] ERROR Request Failed with exception  (io.confluent.rest.exceptions.DebuggableExceptionMapper:103)
javax.ws.rs.NotFoundException: Consumer group offsets could not be found.
```
Most recent testbreak ticket: https://confluentinc.atlassian.net/browse/KREST-2408
Previous testbreak ticket: https://confluentinc.atlassian.net/browse/KREST-2303

### CODE REVIEW

**Comment by ahuang98** [comment]
@rigelbm Wasn't sure if this was the recommended way, but opened this PR to merge the same changes into master.

**Review by dimitarndimitrov — APPROVED** [review]
+1, as the approach sounds reasonable.
Do you think the additional retries are no longer needed?
Do you have an idea what might have caused this suddenly becoming much flakier?

**Comment by ahuang98** [comment]
@dimitarndimitrov 
Since the additional retries were originally added to address the test failure, I decided to revert it (since the issue turned out to be w/ consumer group offsets and not the lag requests). 
For my understanding, did we determine that this is a regression because Jenkins builds /#421 and /#422 failed? 
I'm not sure if I'm looking in the right place or interpreting this correctly, but from /#421 it seems the only change is kafka version `5.5.6-SNAPSHOT` -> `5.5.6`. https://jenkins.confluent.io/job/confluentinc/job/kafka-rest/job/7.0.x/421/ 
Would you happen to know how to find the `5.5.6-SNAPSHOT` image to look at the diffs?

**Comment by ahuang98** [comment]
Seems like Jenkins takes care of merging `7.0.x` into `master`. The build for that commit will fail on a formatting issue though which 840f505 addresses. I'll cherry-pick that change into `7.0.x` and let Jenkins merge it into `master` again.

**Pull request closed without merging**
