### PR TITLE
Bump version to 2.1.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by ijuma** [comment]
retest this please

**Comment by ijuma** [comment]
Review by @miguno

**Comment by ijuma** [comment]
@ewencp maybe you can review this (as Michael may no longer available today) as it fixes the Jenkins build. Also https://github.com/confluentinc/kafka-rest/pull/157

**Comment by ewencp** [comment]
LGTM

**Pull request merged**
