### PR TITLE
Remove V1 APIs and all their dependencies.

### PR DESCRIPTION
**Pull request by rigelbm**

### CODE REVIEW

**Comment by mhowlett** [comment]
at a high level looks fine to me, and i trust you've got it right. if you believe it would be valuable for me to check this in some depth, happy to do so (let me know), else LGTM.

**Comment by ijuma** [comment]
Nice!

**Comment by rigelbm** [comment]
Ignoring Jenkins failure, because it's due to a dependend build. A PR to fix the dependent build is ready, and will be merged after this one.

**Comment by brianbushree** [comment]
@rigelbm I think we need to refactor some stuff [here](https://github.com/confluentinc/confluent-cloud-plugins/blob/master/kafka-rest-healthcheck-plugin/src/main/java/io/confluent/cloud/kafka/rest/health/HealthCheckResource.java) that depends on some of this code

**Pull request merged**
